language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: 0b0oPsjkvPvx6WIxkaJPkjdewnLjaYFwOaVhb7Cm+/bXF/PIOr+r28VJa1GHJl+8fEi1s1c1nY1nm6LKlRdeBRjl3BrSd/e7cqUq+sXym8439Ve/38YtNj/+9bA4d0IAqvplS5xyZs8XNTWaYrh3+jXSTTu5fNmve9NAxHWhX+L6nt0ttn9kdsRXBqBSai95v4mwv1MvhieDhD5URuqCmxazIG6/OYnaKn3lkJ74AW+ont7xDcuEnxIxCTHre9i1TPiVtx4ZSCNutKZyVzINItNWHF62cw2k7s5V3gp/mY997LqgSOp/HZu1jbrThAqzckPed2E9qo5cIRZH8tZ0XiTerrbyJAQEW2GPSS/DZ1551SFeXTU5OV2k4aoEWc5gnONKvjcSVDMqd2qoIOnW4HI0sG/uKhnVjhEq3sUa7/Nf1z1GGHiUmGeeGrOLTEwLYU1bXX5s73PbCug+/mV81iw297/SgVzSDDTplGUssQvsWKtuD7iKsQfSLUkSnQwzY6The3FUXRZvB+dg0Bp3amBI4zZQk8aRQy2Rv4n7cHXLmHX6C7/VdgTOjF+yRuLBuNj5Yc40bt2ZytmHawEP0RoIm7TvgJgLd9jy4OvaahyXmnAYPM4D7XBfZtPSxrQ6nM5VgNwigJVo7yoVJ8LVFp0gppKyNg4bHXOdZVWtr0I=
  app: obscure-mesa-74714
  
  