language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: TGJGsZ8x3cW5toE4muM5QlxVKvpBokHM5eU3AgL3WiGU8McQg2bZBnZxIOiALybtDpNmaPU5SJcyac+W6MLhcqv3NO0TAkc/YP+3TF5X19r04S8XuwphYvt4oTe3yqo0hUZbKQB1BVEorM6JGNyj85eBMZFIMFTBgINWhB/FOdO1eiRbNwlNDpAjJl5cw6kEN/RSP66Blq4QTZu00XA1EmmunRZxwDJPPatbK643zzN8sPWxt0wk4wbjb5U8mGvB4YjzHNL3SKmvCJsaprJvavn1UjuA4sCpVp2aG7JKGn8ZFMHFpA+NW10noYnsR/KOUIOthngmuegXGbF18/2w7bsr0QXtAIR7xcEhoMIVyU9dD2p3BHOtr4XnjTETxIjnV7I2OG7vEzX2HT2IdlujNAvh9Lp6nX8QC3iCiVSyMljoDMyQgj8vUuAsV0k/Pv+TeoVI9mtfDFglYXAc0GpYAxC2nWGxSsAxwiR80xBpjfq4MjtKKBaLtK6wjnCUrf2Xtp9+n6Ry0rfZwag0L9bvyS/xxqOqvb8YVuLhmqZQGfAwfuM19Ii4OO6C04yGkabzt49jos9qJqfpSSFJTDS2jyUHPS5GIgLFXPPQO5AhXR+WZGkdmr7G/W7n6IccXYQEIHwo54B7z3IjVqfvT8l1gpkE5gShviTtqo6Fe6gLVdk=
  app: blog-app-challenge
  on:
    repo: Richardek/blog-app-challenge
